[package]
name = "desktop_core"
edition = { workspace = true }
license = { workspace = true }
version = { workspace = true }
publish = { workspace = true }

[features]
default = [
    "dep:widestring",
    "dep:windows",
    "dep:core-foundation",
    "dep:security-framework",
    "dep:security-framework-sys",
    "dep:zbus",
]
manual_test = []

[dependencies]
anyhow = { workspace = true }
arboard = { workspace = true, features = ["wayland-data-control"] }
base64 = { workspace = true }
bytes = { workspace = true }
dirs = { workspace = true }
futures = { workspace = true }
interprocess = { workspace = true, features = ["tokio"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["io-util", "sync", "macros"] }
tokio-util = { workspace = true, features = ["codec"] }
tracing = { workspace = true }

[target.'cfg(not(windows))'.dependencies]
zeroizing-alloc = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
ashpd = { workspace = true, features = ["background", "clipboard", "remote_desktop", "screencast"] }
homedir = { workspace = true }
libc = { workspace = true }
oo7 = { workspace = true }
zbus = { workspace = true, optional = true }

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = { workspace = true, optional = true }
desktop_objc = { path = "../objc" }
secmem-proc = { workspace = true }
security-framework = { workspace = true, optional = true }
security-framework-sys = { workspace = true, optional = true }

[target.'cfg(windows)'.dependencies]
scopeguard = { workspace = true }
secmem-proc = { workspace = true }
serde_with = { workspace = true, features = ["base64"] }
sha2 = "=0.10.9"
widestring = { workspace = true, optional = true }
win_webauthn = { path = "../win_webauthn" }
windows = { workspace = true, features = [
    "ApplicationModel_PackageExtensions",
    "Storage_Search",
    "Win32_Foundation",
    "Win32_Security_Credentials",
], optional = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }

[lints]
workspace = true
